sudo: required
dist: trusty

#branches:
#  only:
#    - master

#matrix:
#  include:
#    - os: linux
#      dist: trusty
#      sudo: required
#    - os: osx
#      osx_image: xcode8.2
#      sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/swift-3.0.1-release/ubuntu1404/swift-3.0.1-RELEASE/swift-3.0.1-RELEASE-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-3.0.1-RELEASE-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=swift-3.0.1-RELEASE-ubuntu14.04/usr/bin:$PATH    ; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install clang-3.8 lldb-3.8 libicu-dev libkqueue-dev libtool libcurl4-openssl-dev libbsd-dev libblocksruntime-dev build-essential libwrap0-dev libssl-dev libc-ares-dev uuid-dev xsltproc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=/usr/bin/clang-3.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=/usr/bin/clang-3.8 ; fi
  
script:

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.build/debug/HelloWorld ; fi
  
#env:
#  - secure: "TRAVIS-SECRET-ENVIRONMENT-VARIABLE-GOES-HERE"
# This would contain a secret token with your github personal access token

#after_success:
#  - "chmod a+x /home/travis/build/MY-REPO/swift-helloworld-travis/travis-automerge"
#  - "BRANCHES_TO_MERGE_REGEX='MY-DEV-BRANCH' BRANCH_TO_MERGE_INTO=BRANCH-TO-MERGE-TO GITHUB_REPO=MY-REPO/swift-helloworld-travis /home/travis/build/MY-REPO/swift-helloworld-travis/travis-automerge"
